### ISSUE TITLE
Please explain what the plugin does

### ISSUE THREAD

**Issue by s13ffen** [zouyonghao/zotero-sync-to-tablet#26]
I found you mentioned your plugin here: https://github.com/wileyyugioh/zotmoov/issues/44

Please explain what your plugin tries to achieve exactly.
Especially these two features are still not covered by zotmoov:
- Will it create a second "annotated" PDF on retrieval from the table?
- Will it extract annotations into a text note in zotero?

Thanks

**Comment by zouyonghao** [comment]
Hi, I added some explanations to this simple plugin.

> After setting a target directory in the settings, it supports copying the specified file to the target directory and retrieving the file from the target directory (overwrite).
>
> This plugin does not have other features, like extracting annotations.
