### ISSUE TITLE
adding the option of embedding annotations on the pdf

### ISSUE THREAD

**Issue by aquaresima** [zouyonghao/zotero-sync-to-tablet#31]
Hello,

First, thank you a lot for developing this!

I would like to have the option to send the pdf with embedded annotations to my "tablet" folder. 
This can now be achieved by File>Export PDF, however I cannot pull back the pdf in that way.

Would be possible to do a similar thing for the target folder? It would be great if the annotation export is an option (for example, in the menu bar having 'send with/without annotation').

Thanks!

**Comment by zouyonghao** [comment]
Hi,

Thank you for your interest! I'm currently not sure whether to continue this small project, which is a temporary solution for Zotmoov. Zotmoov should support your needs now, but if you think it is still valuable to have the feature you mentioned in this simple plugin, I'll be happy to explore how to implement it later.

Merci!
